name: Build and Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0

    - name: Restore Dependencies
      run: dotnet restore RPBooking/RPBooking.sln

    - name: Build Solution
      run: dotnet build RPBooking/RPBooking.sln --no-restore --configuration Release

    - name: Run xUnit Tests
      run: dotnet run RPBooking/RPBooking/RPBookingAPI.csproj --no-build --configuration Release --verbosity normal 
